---
title: "git_01"
author: "Marcia Alarcon"
date: "September 21, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves 
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Let the bird of loudest lay   
On the sole Arabian tree   
Herald sad and trumpet be,   
To whose sound chaste wings obey.   

But thou shrieking harbinger,   
Foul precurrer of the fiend,   
Augur of the fever's end,   
To this troop come thou not near.   

From this session interdict.  
Every fowl of tyrant wing,    
Save the eagle, feather'd king;   
Keep the obsequy so strict.   

Let the priest in surplice white,   
That defunctive music can,   
Be the death-divining swan,   
Lest the requiem lack his right.   

And thou treble-dated crow,   
That thy sable gender mak'st    
With the breath thou giv'st and tak'st,   
'Mongst our mourners shalt thou go.   